committee/urls.py
from django.urls import path

from result.views import remove_section_from_score
from .views import *

urlpatterns = [
    # path('basic_info/create/', create_basic_info, name="create_basic_info"),
    path('committee/', exam_committee, name="exam_committee"),
    path('committee/edit/<pk>/', edit_exam_committee, name="edit_exam_committee"),
    path('committee/<pk>/', exam_committe_detail, name="exam_committe_detail"),

    path('course/',  course, name="course"),
    path('course/edit/<pk>/', edit_course, name="edit_course"),
    path('course/<pk>/', course_details, name="course_details"),
    
    path('semester/', semester, name="semester"),
    path('semester/edit/<pk>/', edit_semester, name="edit_semester"),
    path('semester/<pk>/', semester_details, name="semester_details"),

    path('academic_year/', academic_year, name="academic_year"),
    path('academic_year/edit/<pk>/', edit_academic_year, name="edit_academic_year"),
    path('academic_year/<pk>/', academic_year_details, name="academic_year_details"),

    path('score/<student_id>/<course>/', student_course_details, name="student_course_details"),
    path('remove_section/<pk>/<section>/', remove_section_from_score, name="remove_section_from_score"),
]

home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    
    path('', views.home, name="dashboard"),
    path('home/', views.bkash, name="bkash")
]
    
    
    

students/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('student/', student, name="student"),
    path('student/<student_id>/', student_detail, name="student_detail"),
    path('student/<student_id>/edit/', edit_student, name="edit_student"),

    path('hall/',  hall, name="hall"),
    path('hall/<pk>/', hall_detail, name="hall_detail"),
    path('hall/<pk>/edit/', edit_hall, name="edit_hall"),
]

committee/models.py
from django.db import models

from user.models import User
from django.db.models import UniqueConstraint

import uuid

class AcademicYear(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)

    class Meta:
        get_latest_by = "-name"

    def __str__(self):
        return self.name


class Semester(models.Model):
    SEMESTER_CHOICE = (
        ('1st', '1st'),
        ('2nd', '2nd'),
        ('3rd', '3rd'),
        ('4th', '4th'),
        ('5th', '5th'),
        ('6th', '6th'),
        ('7th', '7th'),
        ('8th', '8th'),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=20, choices=SEMESTER_CHOICE, null=False, blank=False)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.SET_NULL, blank=True, null=True )

    class Meta:
        ordering = ("-academic_year", 'name')
        constraints = [
            UniqueConstraint(fields=['name',
                'academic_year'],
                name='academic_year_semester_unique',
            ),
        ]

class ExamCommittee(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.SET_NULL, blank=True, null=True )
    semester = models.ManyToManyField(Semester, related_name="exam_committee")
    member = models.ManyToManyField(User, related_name="exam_committee_member")
    chairman = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    tabulator = models.ManyToManyField(User, related_name="tabulator")
    
    class Meta:
        ordering = ('-academic_year',)

class Course(models.Model):  
    TYPE_CHOICE = (
        ('Theory', 'Theory'),
        ('Lab/FieldWork/Project', 'Lab/FieldWork/Project')
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    course_code = models.CharField(max_length=50)
    name = models.CharField(max_length=100)
    teacher = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    examiner = models.ManyToManyField(User, related_name="examiner")
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE, null=False, blank=False)
    credit_point = models.IntegerField()
    course_type = models.CharField(max_length=40, choices=TYPE_CHOICE, null=False, default='Theory', blank=False)
    def __str__(self):
        return self.course_code
    class Meta:
        ordering = ('semester', 'course_code')

students/models.py
from django.db import models
from django_resized import ResizedImageField
from user.models import User
import uuid
# Create your models here.
class Hall(models.Model):
    name = models.CharField(max_length=250, null=False, blank=False)

class Student(models.Model):
    TYPE_CHOICE = (
        ('BSc', 'BSc'),
        ('MSc', 'MSc')
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    full_name = models.CharField(max_length=250, null=True, blank=True)
    student_id =  models.CharField(max_length=10, null=False, blank=False, unique=True)
    degree = models.CharField(max_length=20, choices=TYPE_CHOICE, null=True, blank=True)
    session = models.CharField(max_length=50, null=True, blank=True)
    hall= models.ForeignKey(Hall, on_delete=models.SET_NULL, blank=True, null=True )
    
    class Meta:
        ordering = ('student_id', 'session')
    

committee/forms.py
from django import forms
from .models import *

from django import forms

class ExamCommitteeForm(forms.ModelForm):
    class Meta:
        model = ExamCommittee
        exclude = ('id',)

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        exclude = ('id',)

class SemesterForm(forms.ModelForm):
    class Meta:
        model = Semester
        exclude = ('id',)

class AcademicYearForm(forms.ModelForm):
    class Meta:
        model = AcademicYear
        exclude = ('id',)

students/forms.py
from django import forms
from .models import *


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        exclude = ('id',)

class HallForm(forms.ModelForm):
    class Meta:
        model = Hall
        exclude = ('id',)

committee/views.py
from itertools import groupby
from operator import itemgetter
from django.shortcuts import render
from committee.forms import AcademicYearForm, CourseForm, ExamCommitteeForm, SemesterForm
from django.http import Http404, HttpResponse, JsonResponse
from result.models import Catm, ExamMark, Score

from user.models import User
from .models import AcademicYear, Course, ExamCommittee, Semester
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def exam_committee(request):
    if request.method == "GET":
    #list
        academic_year = request.GET.get('academic_year', None)
        semester = request.GET.get('semester', None)

        print(academic_year, semester)
        query = Q()
        if academic_year:
            query &= Q(academic_year=academic_year)
        if semester:
            query &= Q(semester=semester)
        
        committee_list = ExamCommittee.objects.filter(query).prefetch_related('academic_year', 'semester', 'member', 'chairman', 'tabulator')


        page = request.GET.get('page', 1)
        paginator = Paginator(committee_list, 10)

        try:
            committies = paginator.page(page)
        except PageNotAnInteger:
            committies = paginator.page(1)
        except EmptyPage:
            committies = paginator.page(paginator.num_pages)


        teachers = User.objects.all()
        semesters = Semester.objects.all()
        academic_years = AcademicYear.objects.all()

        return render(request, "committee.html", {"committies": committies, "teachers": teachers, "semesters": semesters, 'academic_years': academic_years, "filters": {"academic_year": academic_year, "semester": semester}})
    
    elif request.method == "POST":
        print(request.POST)
        
        # updated_request = request.POST.copy()
        # updated_request.update({'academic_year': academic_year.id})
        # committee = ExamCommitteeForm(updated_request)
        committee = ExamCommitteeForm(request.POST)
        

        if committee.is_valid():
            committee.save()
            messages.success(request, "Successfully Updated Commttee")
            return JsonResponse({"status": "success", "msg": "Done."}, status=201)
       
        else:
            messages.error(request, "Failed To Update Commttee Information")
            err_msg = ""
            for field, errors in committee.errors.items():
                for error in errors:
                    err_msg += "\n{} - {}".format(field, error)
            return JsonResponse({"status":"error", "msg": err_msg}, status=200)


@login_required()
def edit_exam_committee(request, pk):
    exam_committee = get_object_or_404(ExamCommittee, id=pk)
    if request.method == "GET":
        committies = ExamCommittee.objects.all()
        teachers = User.objects.all()
        semesters = Semester.objects.all()
        academic_years = AcademicYear.objects.all()

        return render(request, 'form/committee_form.html', {
            "action": reverse('edit_exam_committee', args=[pk]),
            "committee": exam_committee,
            "teachers": teachers, 
            "semesters": semesters,
            'academic_years': academic_years
        })

    if request.method == "POST":
        form = ExamCommitteeForm(request.POST, instance=exam_committee)
        if form.is_valid():
            form.save()
            messages.success(request, "Successfully Updated")
            return JsonResponse({"status": "success", "msg": "Done."}, status=201)

        else:
            messages.error(request, "Failed To Update Exam Committee")
            err_msg = ""
            for field, errors in form.errors.items():
                for error in errors:
                    err_msg += "\n{} - {}".format(field, error)
            return JsonResponse({"status":"error", "msg": err_msg}, status=200)
    
    if request.method == "DELETE":
        try:
            exam_committee.delete()
            
            messages.success(request, "Successfully Deleted")
            return JsonResponse({"status": "success", "msg": "Done."}, status=200)
        except Exception as e:
            print(e)
            messages.error(request, "Failed To Update Work Experience")
            return JsonResponse({"status":"error", "msg": "Failed To delete"}, status=200)


def exam_committe_detail(request, pk):

    return render(request, "committee_detail.html")

    
def course(request):
    if request.method == "GET":
    #list
        
        academic_year = request.GET.get('academic_year', None)
        semester = request.GET.get('semester', None)

        # print(academic_year, semester)
        query = Q()
        if academic_year:
            query &= Q(semester__academic_year=academic_year)
        if semester:
            query &= Q(semester=semester)
        
        course_list = Course.objects.filter(query).prefetch_related('teacher', 'examiner', 'semester')


        page = request.GET.get('page', 1)
        paginator = Paginator(course_list, 10)

        try:
            courses = paginator.page(page)
        except PageNotAnInteger:
            courses = paginator.page(1)
        except EmptyPage:
            courses = paginator.page(paginator.num_pages)


        teachers = User.objects.all()
        semesters = Semester.objects.all()
        academic_years = AcademicYear.objects.all()

        
        return render(request, "course.html", {"courses": courses, "teachers": teachers, "semesters": semesters, 'academic_years': academic_years, "filters": {"academic_year": academic_year, "semester": semester}})
    
    elif request.method == "POST":
        print(request.POST)
        course = CourseForm(request.POST)
        if course.is_valid():
            course.save()
            messages.success(request, "Successfully Updated Transaction Detail")
            return JsonResponse({"status": "success", "msg": "Done."}, status=201)
       
        else:
            messages.error(request, "Failed To Update Educational Background")
            err_msg = ""
            for field, errors in course.errors.items():
                for error in errors:
                    err_msg += "\n{} - {}".format(field, error)
            return JsonResponse({"status":"error", "msg": err_msg}, status=200)


def course_details(request, pk):
    course = get_object_or_404(Course, id=pk)
    scores = Score.objects.filter(course=course).prefetch_related('catm', 'catm__student', 'section_a__course', 'section_b__course', 'course')
    exam_marks = ExamMark.objects.filter(course=course, is_allocated=False).order_by('section')
    return render(request, 'course_details.html', {"course": course, "scores": scores, "exam_marks": exam_marks})

def student_course_details(request, student_id, course):
    if request.method == "GET":
        # course = get_object_or_404(Course, id=course)
        score = get_object_or_404(Score, catm__student__student_id=student_id, course__id=course)

        return render(request, 'student_course_details.html', {"score": score} )

@login_required()
def edit_course(request, pk):
    course = get_object_or_404(Course, id=pk)
    if request.method == "GET":
        # committies = ExamCommittee.objects.all()
        teachers = User.objects.all()
        semesters = Semester.objects.all()
        academic_years = AcademicYear.objects.all()

        return render(request, 'form/course_form.html', {
            "action": reverse('edit_course', args=[pk]),
            "course": course,
            "teachers": teachers, 
            "semesters": semesters,
            'academic_years': academic_years
        })

    if request.method == "POST":
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            messages.success(request, "Successfully Updated")
            return JsonResponse({"status": "success", "msg": "Done."}, status=201)

        else:
            messages.error(request, "Failed To Update Work Experience")
            err_msg = ""
            for field, errors in form.errors.items():
                for error in errors:
                    err_msg += "\n{} - {}".format(field, error)
            return JsonResponse({"status":"error", "msg": err_msg}, status=200)
    
    if request.method == "DELETE":
        try:
            course.delete()
            
            messages.success(request, "Successfully Deleted")
            return JsonResponse({"status": "success", "msg": "Done."}, status=200)
        except Exception as e:
            print(e)
            messages.error(request, "Failed To Update Work Experience")
            return JsonResponse({"status":"error", "msg": "Failed To delete"}, status=200)

def semester(request):
    if request.method == "GET":
        semesters = Semester.objects.all()
        academic_years = AcademicYear.objects.all()


        academic_year = request.GET.get('academic_year', None)

        query = Q()
        if academic_year:
            query &= Q(academic_year=academic_year)
        
        semesters_list = Semester.objects.filter(query)
        page = request.GET.get('page', 1)
        paginator = Paginator(semesters_list, 10)
        

        try:
            semesters = paginator.page(page)
        except PageNotAnInteger:
            semesters = paginator.page(1)
        except EmptyPage:
            semesters = paginator.page(paginator.num_pages)


        return render(request, 'semesters.html', {
            "semesters": semesters,
            "semester_options": ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th'],
            'academic_years': academic_years,
            "filters": {'academic_year': academic_year}
            })

    elif request.method == "POST":

templates/card/academic_year.html
{% load static %}

<div class="card  border border-light mb-2">
    <div class="card-header bg-default" id="academicyear{{forloop.counter}}e">
        <div class="row" data-toggle="collapse" data-target="#collapseacademicyear{{forloop.counter}}"
            aria-expanded="true" aria-controls="collapseacademicyear{{forloop.counter}}">

            <div class="col-10">
                <div class="d-flex align-items-center">
                    <div class="avatar flex-shrink-0 me-3 align-items-center">
                        <img src="{% static 'img/academic_year.svg' %}" alt="academic year svg" class="rounded">
                    </div>
                    <div class="d-flex w-100 flex-wrap align-items-baseline justify-content-between gap-2">

                        <div class="me-2">
                            <small class="text-muted d-block mb-1">Academic Year</small>
                            <p class="mb-0">{{academic_year.name}}</p>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-2 d-flex justify-content-end align-items-center gap-1">

                <div class="dropdown">
                    <button class="btn p-0" type="button" id="application{{forloop.counter}}" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="bx bx-dots-vertical-rounded"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="application{{forloop.counter}}">
                        
                        <a href="{% url 'academic_year_details' academic_year.id %}"  class="dropdown-item">
                            <span class="">View</span>
                          </a>
                        
                        {% url 'edit_academic_year' academic_year.id as academic_year_action %}
                   
                        <a href="{{academic_year_action}}" class="ajax-delete dropdown-item">
                          <span class="">Delete</span>
                        </a>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/card/committee.html
{% load static %}

<div class="card  border border-light mb-2">
    <div class="card-header bg-default" id="application{{forloop.counter}}e">
      <div class="row" data-toggle="collapse" data-target="#collapseapplication{{forloop.counter}}" aria-expanded="true"
        aria-controls="collapseapplication{{forloop.counter}}">
       
        <div class="col-10">
          <div class="d-flex align-items-center">
            <div class="avatar flex-shrink-0 me-3 align-items-center">
              <img src="{% static 'img/team.png' %}" alt="User" class="rounded">
            </div>
            <div class="d-flex w-100 flex-wrap align-items-baseline justify-content-between gap-2">
              
              <div class="me-2">
                <small class="text-muted d-block mb-1">Academic Year</small>
                <p class="mb-0">{{committee.academic_year.name}}</p>
              </div>
              <div class="me-2">
                <small class="text-muted d-block mb-1">Semester</small>
                <p class="mb-0">{% for semester in committee.semester.all %} <span class="badge rounded-pill bg-label-primary">{{ semester.name }}</span>{%endfor%}</p>
              </div>
              <div class="me-2">
                <small class="text-muted d-block mb-1">Chairman</small>
                <p class="mb-0"><img src="{% if committee.chairman.gender == 0 %}
                  {% static 'img/male_avatar.svg' %}
                  {% else %}
                  {% static 'img/female_avatar.svg' %}
                  {% endif %}" class="avatar-xs" alt=""> {{committee.chairman.full_name }}</p>
              </div>
              <div class="me-2">
                <small class="text-muted d-block mb-1">Member</small>
                {% for member in committee.member.all  %}<p class="mb-0">
                  <img src="{% if member.gender == 0 %}
                  {% static 'img/male_avatar.svg' %}
                  {% else %}
                  {% static 'img/female_avatar.svg' %}
                  {% endif %}" class="avatar-xs" alt="">{{ member.full_name }}
                </p>{% endfor %} </p>
              </div>
              </div>
              </div>
              </div>

              <div class="col-2 d-flex justify-content-end align-items-center gap-1">
               
                <div class="dropdown">
                    <button class="btn p-0" type="button" id="application{{forloop.counter}}" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="bx bx-dots-vertical-rounded"></i>
                    </button>
          
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="application{{forloop.counter}}">
                      
                      <a data-url="{% url 'edit_exam_committee' committee.id %}"  data-bs-toggle="modal"
                      data-title="Edit Exam Committee" data-bs-target="#UpdateFormModal" class="dropdown-item">
                      <span class="">Edit</span>
                      </a>
              
                    
                    </div>
                  </div>
                  </div>


                
    
                
            </div>
            </div>
          </div>

        
       
           

        

templates/card/course.html
{% load static %}

<div class="card  border border-light mb-2">
    <div class="card-header bg-default" id="application{{forloop.counter}}e">
      <div class="row" data-toggle="collapse" data-target="#collapseapplication{{forloop.counter}}" aria-expanded="true"
        aria-controls="collapseapplication{{forloop.counter}}">
       
        <div class="col-10">
          <div class="d-flex align-items-center">
            <div class="avatar flex-shrink-0 me-3 align-items-center">
              <img src="{% static 'img/course.svg' %}" alt="User" class="rounded">
            </div>
            <div class="d-flex w-100 flex-wrap align-items-baseline justify-content-between gap-2">
              
              <div class="me-2">
                <small class="text-muted d-block mb-1">Academic Year</small>
                <p class="mb-0">{{course.semester.academic_year}}</p>
              </div>

              <div class="me-2">
                <small class="text-muted d-block mb-1">Course</small>
                <p class="mb-0" data-bs-toggle="tooltip" data-bs-offset="0,4" 
                data-bs-placement="right" data-bs-html="true" 
                title="" data-bs-original-title="<span>{{course.name}}<br>Credit:{{course.credit_point}}<br>Semester:{{ course.semester.name }}</span>">
                {{course.course_code}}
                </p>
               
              </div>
             
              <div class="me-2">
                <small class="text-muted d-block mb-1">Teacher</small>
                <p class="mb-0"><img src="{% if course.teacher.gender == 0 %}
                  {% static 'img/male_avatar.svg' %}
                  {% else %}
                  {% static 'img/female_avatar.svg' %}
                  {% endif %}" class="avatar-xs" alt=""> {{course.teacher.full_name }}</p>
              </div>
              <div class="me-2">
                <small class="text-muted d-block mb-1">Examiner</small>
                {% for member in course.examiner.all  %}<p class="mb-0">
                  <img src="{% if member.gender == 0 %}
                  {% static 'img/male_avatar.svg' %}
                  {% else %}
                  {% static 'img/female_avatar.svg' %}
                  {% endif %}" class="avatar-xs" alt="">{{ member.full_name }}
                </p>{% endfor %} </p>
              </div>
              </div>
              </div>
              </div>

              <div class="col-2 d-flex justify-content-end align-items-center gap-1">
               
                <div class="dropdown">
                    <button class="btn p-0" type="button" id="application{{forloop.counter}}" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="bx bx-dots-vertical-rounded"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="application{{forloop.counter}}">
                      {% if disable_view == True %}
                     
                      {% else %}
                      <a href="{% url 'course_details' course.id %}"  class="dropdown-item">
                        <span class="">View</span>
                         </a>
                         {% endif %}
                      {% url 'edit_course' course.id as course_action %}
                      <a data-url="{{course_action}}"  data-bs-toggle="modal"
                      data-title="Edit Course" data-bs-target="#UpdateFormModal" class="dropdown-item">
                      <span class="">Edit</span>
                      </a>
                      <a href="{{course_action}}"  class="ajax-delete dropdown-item">
                        <span class="">Delete</span>
                         </a>
              
                    
                    </div>
                  </div>
                  </div>


                
    
                
            </div>
            </div>
          </div>

        
       
           

        

templates/card/course_detail_card.html
<div class="card">
    <div class="card-body">
        <div class="row">

            <div class="my-2">
              <h5 class="fw-bolder">Course Information</h5>
       
                <table class="table info-table table-borderless">
                  <tbody>
                    
                    <tr>
                      <td class="text-end"><small class="text-light fw-semibold">Course Code: </small></td>
                      <td class="">
                        <p class="mb-0"> {{course.course_code}}</p>
                      </td>
                    </tr>
                    <tr>
                      <td class="text-end"><small class="text-light fw-semibold">Course Name: </small></td>
                      <td class="">
                        <p class="mb-0"> {{course.name}}</p>
                      </td>
                    </tr>
                    <tr>
                        <td class="text-end"><small class="text-light fw-semibold">Semester : </small></td>
                        <td class="">
                          <p class="mb-0">{{course.semester.name}}</p>
                        </td>
                      </tr>
                      <tr>
                        <td class="text-end"><small class="text-light fw-semibold">Academic Year : </small></td>
                        <td class="">
                          <p class="mb-0">{{course.semester.academic_year}}</p>
                        </td>
                      </tr>
                  </tbody>
                </table>
              
            </div>
          </div>
      
    </div>
</div>
   

templates/card/file.html
{% load file_extension %}
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bolder text-primary ">Project Files
      {% if not request.user.user_type == "0" %}
      <div class="float-right">
        <a href="{% url 'project_file_upload' id %}" data-toggle="modal" data-title="Upload New File"
          data-target="#CallBackForm" class="btn btn-sm btn-primary">New File</a>
      </div>
      {% endif %}
    </h6>
  </div>

  <div class="card-body">
    <div class="row p-1">
        {% if files %}
        {% for file in files %}
          {% if request.user.user_type == '0' and file.visible_to_client == 0 %}

          {% else %}
          <div class="col-6">
            <div class="row my-1 p-1 d-flex align-items-center">
              <div class="col-2">
                {% with ext=file.document.url|file_extension %}
                  {% if ext == "png" or ext == "jpg" or ext == "jpeg" %}
                    <i class="fas fa-2x text-info fa-file-image"></i>
                  {% elif ext == "xlsx" or ext == "xls" or ext == "csv" %}
                  <i class="fas fa-2x text-success font-weight-bolder fa-file-excel"></i>
                  {% elif ext == "pdf" %}
                    <i class="fas fa-2x text-danger font-weight-bolder fa-file-pdf"></i>
                  {% elif ext == "ppt" or ext == "pptx" or ext == "ppsx" %}
                    <i class="fas fa-2x text-warning font-weight-bolder fa-file-powerpoint"></i>
                  {% elif ext == "doc" or ext == "docx" %}
                    <i class="fas fa-2x text-primary font-weight-bolder fa-file-word"></i>
                  {% else %}
                  <i class="fas fa-2x text-secondary font-weight-bolder fa-file"></i>
                  {% endif %}

                  {% endwith %}
              </div>
              <div class="col-7">
                <div class="">{{file.filename}}</div>
                <div class="text-sm text-muted"><small>{{file.inserted_at|date:'M d Y'}}</small></div>
              </div>
              <div class="col-3">
                <a href="{{file.document.url }}" class="btn btn-primary btn-sm text-center" download="download">
                  <i class="fas fa-download"></i>
               </a>
              </div>
            </div>
          </div>
          {% endif %}
        {% endfor %}
        {% else %}
        <div class="mx-auto"> No files Uploaded yet</div>
        {% endif %}
    </div>
       
       









  </div>
</div>

templates/card/hall.html
{% load static %}

<div class="card  border border-light mb-2">
    <div class="card-header bg-default" id="application{{forloop.counter}}e">
      <div class="row" data-toggle="collapse" data-target="#collapseapplication{{forloop.counter}}" aria-expanded="true"
        aria-controls="collapseapplication{{forloop.counter}}">
       
        <div class="col-10">
               
                <div class="d-flex align-items-center">
                    

                    <div class="flex-grow-1">
                        <span class="fw-semibold d-block">{{hall.name}}</span>
                        <span class="font-weight-bold">Student Allocated: </span> {{hall.student_set.all.count}} <br>

                    </div>
                </div>
 
        </div>
       
        <div class="col-2 d-flex justify-content-end align-items-center gap-1">
          <div class="dropdown">
              <button class="btn p-0" type="button" id="application{{forloop.counter}}" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="bx bx-dots-vertical-rounded"></i>
              </button>

              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="application{{forloop.counter}}">
                
              
                {% url 'edit_hall' hall.id as hall_action %}
                <a data-url="{{hall_action}}"  data-bs-toggle="modal" data-title="Edit Hall" data-bs-target="#UpdateFormModal" class="dropdown-item">
                <span class="">Edit</span>
                </a>
                <a href="{{hall_action}}"  class="ajax-delete dropdown-item">
                  <span class="">Delete</span>
                   </a>
              </div>
            </div>
            </div>

      </div>
    </div>
  </div>