home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    
    path('', views.home, name="dashboard"),
    path('home/', views.bkash, name="bkash")
]
    
    
    

committee/models.py
from django.db import models

from user.models import User
from django.db.models import UniqueConstraint

import uuid

class AcademicYear(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)

    class Meta:
        get_latest_by = "-name"

    def __str__(self):
        return self.name


class Semester(models.Model):
    SEMESTER_CHOICE = (
        ('1st', '1st'),
        ('2nd', '2nd'),
        ('3rd', '3rd'),
        ('4th', '4th'),
        ('5th', '5th'),
        ('6th', '6th'),
        ('7th', '7th'),
        ('8th', '8th'),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=20, choices=SEMESTER_CHOICE, null=False, blank=False)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.SET_NULL, blank=True, null=True )

    class Meta:
        ordering = ("-academic_year", 'name')
        constraints = [
            UniqueConstraint(fields=['name',
                'academic_year'],
                name='academic_year_semester_unique',
            ),
        ]

class ExamCommittee(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.SET_NULL, blank=True, null=True )
    semester = models.ManyToManyField(Semester, related_name="exam_committee")
    member = models.ManyToManyField(User, related_name="exam_committee_member")
    chairman = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    tabulator = models.ManyToManyField(User, related_name="tabulator")
    
    class Meta:
        ordering = ('-academic_year',)

class Course(models.Model):  
    TYPE_CHOICE = (
        ('Theory', 'Theory'),
        ('Lab/FieldWork/Project', 'Lab/FieldWork/Project')
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    course_code = models.CharField(max_length=50)
    name = models.CharField(max_length=100)
    teacher = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    examiner = models.ManyToManyField(User, related_name="examiner")
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE, null=False, blank=False)
    credit_point = models.IntegerField()
    course_type = models.CharField(max_length=40, choices=TYPE_CHOICE, null=False, default='Theory', blank=False)
    def __str__(self):
        return self.course_code
    class Meta:
        ordering = ('semester', 'course_code')

templates/tables/exam_marks_table.html
{% load static %}
<div class="table-responsive text-nowrap" >
    <table class="table card-table table-hover exam_mark-table" id="">
      <thead>
        <tr>
         <th>SL No</th>
          <th>Code No</th>
          <th>Mark</th>
         
        
          <th>Actions</th>
        </tr>
      </thead>
      <tbody class="table-border-bottom-0">
        {% for exam_mark in exam_marks %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{exam_mark.code_no}}</td>
          <td>{{exam_mark.marks}}</td>
        
          <td>
            <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
              <a data-url="{% url 'edit_exam_mark' exam_mark.id %}" aria-labelledby="exammark{{forloop.counter}}" data-bs-toggle="modal"
              data-title="Edit Exam Mark " data-bs-target="#UpdateFormModal" class="me-1 btn btn-link btn-sm btn-outline-secondary"><i class="bx bx-edit"></i></a>
            <a href="{% url 'edit_exam_mark' exam_mark.id %}"  class="btn btn-sm btn-link btn-outline-danger ajax-delete "><i class="bx bx-trash"></i></a>
           
            </div>
              
          </td>
        </tr>
       {% endfor %}

      </tbody>
    </table>
  </div>
  <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.bootstrap5.min.css' %}">


  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap5.min.js' %}"></script>


  {% if split_search == True  %}
  <script>
$(document).ready(function () {
    var table = $('.exam_mark-table').DataTable({ 
          paging: false,
            info:false,
            retrieve:true
          });

    $('.table-search').keyup(function () {
        table.search($(this).val()).draw();
    });
});
  </script>
  
{% else %}

<script>
 
  $(document).ready(function () {
    $('.exam_mark-table').DataTable({
      paging: false,
        info:false,
        retrieve:true
    });
  });
</script>

{% endif %}

templates/tables/non_theory_score_table.html
{% load static %}
<div class="table-responsive text-nowrap" >
    <table class="table card-table table-hover" id="catm-table">
      <thead>
        <tr>
          <th>Student</th>
          <th>Mark.</th>
          <th>Grade</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody class="table-border-bottom-0">
        {% for score in scores %}
        <tr>
          <td>{{score.student.student_id}}</td>
          <td>{{score.mark_obtained}}</td>
          <td>{{score.letter_grade|default:''}}</td>
          <td>
            <div class="dropdown">
              <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                <i class="bx bx-dots-vertical-rounded"></i>
              </button>
             
            </div>
          </td>
        </tr>
       {% endfor %}

      </tbody>
    </table>
  </div>
  <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.bootstrap5.min.css' %}">


  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap5.min.js' %}"></script>


  {% if split_search == True  %}
  <script>
$(document).ready(function () {
    var table = $('#catm-table').DataTable({ 
          paging: false,
            info:false
          });

    $('#table-search').keyup(function () {
        table.search($(this).val()).draw();
    });
});
  </script>
  
{% else %}

<script>
 
  $(document).ready(function () {
    $('#payment-table').DataTable({
      paging: false,
        info:false
    });
  });
</script>

{% endif %}

templates/tables/score_non_theory_table.html
{% load static %}
{% load calculate_total %}


<div class="table-responsive text-nowrap" >
    <table class="table card-table table-hover" id="score-table">
      <thead>
        <tr>
          <th>Student</th>
          <th>MO</th>
          <th>LG</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody class="table-border-bottom-0">
        {% for score in scores %}
        <tr>
          <td>{{score.student.student_id}}</td>
          <td>{{score.mark_obtained }}</td>
          <td>{{score.letter_grade|default:'F'}}</td>
          <td>
            <div class="dropdown">
              <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                <i class="bx bx-dots-vertical-rounded"></i>
              </button>
             
            </div>
          </td>
        </tr>
       {% endfor %}

      </tbody>
    </table>
  </div>
  <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.bootstrap5.min.css' %}">


  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap5.min.js' %}"></script>


  {% if split_search == True  %}
  <script>
$(document).ready(function () {
    var table = $('#score-table').DataTable({ 
          paging: false,
            info:false
          });

    $('#table-search').keyup(function () {
        table.search($(this).val()).draw();
    });
});
  </script>
  
{% else %}

<script>
 
  $(document).ready(function () {
    $('#score-table').DataTable({
      paging: false,
        info:false
    });
  });
</script>

{% endif %}

templates/tables/score_table.html
{% load static %}
{% load calculate_total %}


<div class="table-responsive text-nowrap" >
    <table class="table card-table table-hover" id="score-table">
      <thead>
        <tr>
          <th>Student</th>
          <th>catm</th>
          <th>section A</th>
          <th>Section B</th>

          <th>Actions</th>
        </tr>
      </thead>
      <tbody class="table-border-bottom-0">
        {% for score in scores %}
        <tr>
          <td>{{score.catm.student.student_id}}</td>
          <td>{% calculate_catm score.catm %}</td>
          <td>{{score.section_a.marks}}</td>
          <td>{{score.section_b.marks}}</td>

          <td>
            <div class="dropdown">
              <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                <i class="bx bx-dots-vertical-rounded"></i>
              </button>
             
            </div>
          </td>
        </tr>
       {% endfor %}

      </tbody>
    </table>
  </div>
  <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.bootstrap5.min.css' %}">


  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap5.min.js' %}"></script>


  {% if split_search == True  %}
  <script>
$(document).ready(function () {
    var table = $('#score-table').DataTable({ 
          paging: false,
            info:false
          });

    $('#table-search').keyup(function () {
        table.search($(this).val()).draw();
    });
});
  </script>
  
{% else %}

<script>
 
  $(document).ready(function () {
    $('#score-table').DataTable({
      paging: false,
        info:false
    });
  });
</script>

{% endif %}

templates/tables/semester_student_table.html
{% load static %}
{% load calculate_total %}
<div class="table-responsive text-nowrap" >
    <table class="table card-table table-hover exam_mark-table" id="">
      <thead>
        <tr>
    
          <th>Code No</th>
          <th>Credit</th>
          <th>Mark</th>
          <th>Grade</th>
            
          <!-- <th>Actions</th> -->
        </tr>
      </thead>
      <tbody class="table-border-bottom-0">
        {% for score in scores %}
        <tr>
      
          <td>{{score.course.course_code}}</td>
          <th>{{score.course.credit_point}}</th>
          {% get_score_improvement score as sc %}
          <td>{{sc.mark_obtained|default:""}}</td>
            <td>{{sc.letter_grade|default:""}}</td>
          <!-- <td>
            <div class="dropdown">
              <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                <i class="bx bx-dots-vertical-rounded"></i>
              </button>
             
            </div>
          </td> -->
        </tr>
       {% endfor %}
       {% for course in unallocated %}
        <tr>
      
          <td>{{course.course_code}}</td>
          <th>{{course.credit_point}}</th>

          <td></td>
            <td></td>
          <!-- <td>
            <div class="dropdown">
              <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                <i class="bx bx-dots-vertical-rounded"></i>
              </button>
             
            </div>
          </td> -->
        </tr>
       {% endfor %}

      </tbody>
    </table>
  </div>
  <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.bootstrap5.min.css' %}">


  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap5.min.js' %}"></script>


  {% if split_search == True  %}
  <script>
$(document).ready(function () {
    var table = $('.exam_mark-table').DataTable({ 
          paging: false,
            info:false,
            retrieve:true
          });

    $('.table-search').keyup(function () {
        table.search($(this).val()).draw();
    });
});
  </script>
  
{% else %}

<script>
 
  $(document).ready(function () {
    $('.exam_mark-table').DataTable({
      paging: false,
        info:false,
        retrieve:true
    });
  });
</script>

{% endif %}

templates/tables/student_score_table.html
{% load static %}
{% load calculate_total %}


<div class="table-responsive text-nowrap" >
    <table class="table card-table table-hover" id="score-table">

        
      <thead>
        <tr>
          <th>Student</th>
            {% for course in semester.course_set.all %}
                <th> {{course.course_code}} </th> 
            {% endfor %}
          <th>Actions</th>
        </tr>
      </thead>
      <tbody class="table-border-bottom-0">

        {% for student, value in scores.items %}
        <tr>
          <td>{{student.student_id}}</td>

            {% for co in semester.course_set.all %}
                    {% with value|hash:co.course_code as score %}
                        {% get_score_improvement score.0 as sc %}
                    <td>{{ sc.letter_grade|default:""}}</td>

                    {% endwith %}
            {% endfor %}
            
            
      

          <td>
            <div class="dropdown">
              <div>
                <a href="{% url 'generate_grade_sheet' semester.id student.student_id %}" class="btn btn-outline-primary"> <i class="bx bx-download"></i></a>
            </div>
             
            </div>
          </td>
        </tr>
       {% endfor %}

      </tbody>
    </table>
  </div>
  <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.bootstrap5.min.css' %}">


  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap5.min.js' %}"></script>


  {% if split_search == True  %}
  <script>
$(document).ready(function () {
    var table = $('#score-table').DataTable({ 
          paging: false,
            info:false
          });

    $('#table-search').keyup(function () {
        table.search($(this).val()).draw();
    });
});
  </script>
  
{% else %}

<script>
 
  $(document).ready(function () {
    $('#score-table').DataTable({
      paging: false,
        info:false
    });
  });
</script>

{% endif %}

templates/tables/theory_score_table.html
{% load static %}
<div class="table-responsive text-nowrap" >
    <table class="table card-table table-hover" id="catm-table">
      <thead>
        <tr>
          <th>Student</th>
          <th>Attd.</th>
          <th>Ct 1</th>
          <th>Ct 2</th>
          <th>Ct 3</th>
          <th>Ct 4</th>

          <th>CATM</th>
          <th>Section A</th>
          <th>Section B</th>
          <th>MO</th>
          <th>LG</th>
        </tr>
      </thead>
      <tbody class="table-border-bottom-0">
        {% for score in scores %}
        <tr>
          <td><a href="#" data-url="{% url 'student_course_details' score.catm.student.student_id score.course.id %}" aria-labelledby="studentscore{{forloop.counter}}" data-bs-toggle="modal"
            data-title="Score Details" data-bs-target="#ScoreViewModal"> {{score.catm.student.student_id}} </a> 
          </td>
          <td>{{score.catm.attendance}}</td>
          <td>{{score.catm.ct_1}}</td>
          <td>{{score.catm.ct_2}}</td>
          <td>{{score.catm.ct_3}}</td>
          <td>{{score.catm.ct_4|default:''}}</td>
          
          <td>{{score.catm.total}}</td>
          <td>{{score.section_a.marks}}</td>
          <td>{{score.section_b.marks}}</td>
          <td>{{score.mark_obtained|default:0.00}}</td>
          <td>{{score.letter_grade|default:'F'}}</td>
         
        </tr>
       {% endfor %}

      </tbody>
    </table>
  </div>
  <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.bootstrap5.min.css' %}">


  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap5.min.js' %}"></script>


  {% if split_search == True  %}
  <script>
$(document).ready(function () {
    var table = $('#catm-table').DataTable({ 
          paging: false,
            info:false
          });

    $('#table-search').keyup(function () {
        table.search($(this).val()).draw();
    });
});
  </script>
  
{% else %}

<script>
 
  $(document).ready(function () {
    $('#payment-table').DataTable({
      paging: false,
        info:false
    });
  });
</script>

{% endif %}